[package]
authors = ["David Karrick <the.white.wolf.is.1337@gmail.com>"]
edition = "2018"
name = "nxpkgr"
version = "0.1.0"
license = "MIT"
description = "A NixOS installer program"
readme = "README.md"
homepage = "https://github.com/Th3Whit3Wolf/nixosInstaller"

[dependencies]
# Async Runtime
smol = "1.2.5"
# HTTP
surf = "2.2.0"
# Database
sled = "0.34.6"
byteorder = "1.4.3"
zerocopy = "0.5.0"
# JSON
nanoserde = "0.1.29"
# TOML decode
tomboy-toml-dom = "0.1.21"
# Colorful fork of pico-args
pico-args = { path = "./pico-args" }

# Log
log = "0.4"
pretty_env_logger = "0.4.0"

# Errors
eyre = "0.6.5"
color-eyre = "0.5"
thiserror = "1.0.26"

# displaydoc = "0.2"
coarsetime = "0.1.19"
fancy-regex = "0.7.0"

